/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package example

import mindustry.mod.Mod
import arc.util.Log
import arc.Events
import mindustry.game.EventType.ClientLoadEvent
import arc.util.Time
import mindustry.ui.dialogs.BaseDialog
import arc.Core

class ExampleScalaMod extends Mod {
  Log.info("Loaded ExampleScalaMod constuctor.".asInstanceOf[Object])
  Events.on(classOf[ClientLoadEvent], new arc.func.Cons[ClientLoadEvent] {
    override def get(t: ClientLoadEvent) = {
      Time.runTask(10f, () => {
      val dialog = new BaseDialog("frog")
      dialog.cont.add("behold").row()
      //mod sprites are prefixed with the mod name (this mod is called 'example-scala-mod' in its config)
      dialog.cont.image(Core.atlas.find("example-scala-mod-frog")).pad(20f).row()
      dialog.cont.button("I see", dialog.hide _).size(100f, 50f)
      dialog.show()
    })
    }
  })
}